# Generated by Django 5.1.7 on 2025-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
