# Generated by Django 5.1.7 on 2025-04-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_user_nom_user_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
    ]
