# Generated by Django 5.2 on 2025-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bijou',
        ),
        migrations.AddField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('OR', 'OR'), ('Argent', 'Argent'), ('OR massive', 'OR massive')], default='Non defini', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='numero',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
