# Generated by Django 5.2 on 2025-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_delete_bijou_product_materiaux_product_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling')], default='Non defini', max_length=50),
        ),
    ]
