# Generated by Django 5.2 on 2025-07-15 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_product_materiaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('materiaux', models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms')], default='Non defini', max_length=50)),
                ('numero', models.IntegerField(null=True, unique=True)),
                ('category', models.CharField(choices=[('collier', 'Collier'), ('bague', 'Bague'), ('cheville', 'Bracelet de cheville'), ('poignee', 'Bracelet'), ('main', 'Bijou de main'), ('boucle', "Boucle d'oreille")], default='Non defini', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms')], default='Non defini', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_type', models.CharField(choices=[('collier', 'Collier'), ('poignee', 'Bracelet'), ('cheville', 'Cheville')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sales')),
            ],
        ),
    ]
