# Generated by Django 5.2 on 2025-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_sales_alter_product_materiaux_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='category',
            field=models.CharField(choices=[('collier', 'Collier'), ('bague', 'Bague'), ('cheville', 'Bracelet de cheville'), ('poignee', 'Bracelet'), ('main', 'Bijou de main'), ('boucle', "Boucle d'oreille")], default='Non defini', max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='materiaux',
            field=models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms')], default='Non defini', max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='numero',
            field=models.CharField(choices=[('collier', 'Collier'), ('bague', 'Bague'), ('cheville', 'Bracelet de cheville'), ('poignee', 'Bracelet'), ('main', 'Bijou de main'), ('boucle', "Boucle d'oreille")], default='Non defini', max_length=255),
        ),
    ]
