# Generated by Django 5.2 on 2025-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_cartitem_user_sales_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='wear_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli / Gold filled', 'Or rempli / Gold filled'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms'), ('Tennis', 'Tennis')], default='Non defini', max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='category',
            field=models.CharField(choices=[('Collier', 'Collier'), ('Bague', 'Bague'), ('Bracelet de cheville', 'Bracelet de cheville'), ('Bracelet', 'Bracelet'), ('Bijou de main', 'Bijou de main'), ('Boucle doreille', 'Boucle doreille')], default='Non defini', max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='materiaux',
            field=models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli / Gold filled', 'Or rempli / Gold filled'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms'), ('Tennis', 'Tennis')], default='Non defini', max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='numero',
            field=models.CharField(choices=[('Collier', 'Collier'), ('Bague', 'Bague'), ('Bracelet de cheville', 'Bracelet de cheville'), ('Bracelet', 'Bracelet'), ('Bijou de main', 'Bijou de main'), ('Boucle doreille', 'Boucle doreille')], default='Non defini', max_length=255),
        ),
    ]
