# Generated by Django 5.2 on 2025-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_cartitem_wear_type_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='numero',
            field=models.CharField(default='Non defini', max_length=255),
        ),
    ]
