# Generated by Django 5.2 on 2026-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_order_phone_orderitem_is_treated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_treated',
        ),
        migrations.AddField(
            model_name='order',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
    ]
