# Generated by Django 5.2 on 2026-01-12 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_orderitem_is_treated_order_is_treated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sales'),
        ),
    ]
