# Generated by Django 5.2 on 2026-01-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_orderitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cou',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('Or massif 14k', 'Or massif 14k'), ('Or massif 10k', 'Or massif 10k'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms'), ('Tennis', 'Tennis')], default='Non defini', max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sales',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
