# Generated by Django 5.2 on 2026-01-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_product_cou_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
