# Generated by Django 5.2 on 2026-02-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_order_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_pdf',
        ),
    ]
