# Generated by Django 5.2 on 2026-02-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_remove_order_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('Or massif', 'Or massif'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling'), ('Charms', 'Charms'), ('Tennis', 'Tennis')], default='Non defini', max_length=50),
        ),
    ]
