# Generated by Django 5.2 on 2026-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_product_materiaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Canada', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='materiaux',
            field=models.CharField(choices=[('Or massif', 'Or massif'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling')], default='Non defini', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='category',
            field=models.CharField(choices=[('Collier', 'Collier'), ('Chaînes', 'Chaînes'), ('Bijoux de mains', 'Bijoux de mains'), ('Bracelet', 'Bracelet'), ('Accessoires', 'Accessoires'), ('Boucle doreille', 'Boucle doreille')], default='Non defini', max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='materiaux',
            field=models.CharField(choices=[('Or massif', 'Or massif'), ('Or rempli', 'Or rempli'), ('Argent sterling', 'Argent sterling')], default='Non defini', max_length=255),
        ),
    ]
