# Generated by Django 5.2 on 2026-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_order_country_alter_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='materiaux',
            field=models.CharField(choices=[('Acier inoxydable', 'Acier inoxydable'), ('Or remplie', 'Or remplie'), ('Argent 925', 'Argent 925'), ('plaqué or', 'plaqué or')], default='Non defini', max_length=255),
        ),
    ]
